LSTM:
  embedding:
    path_to_embedding: ../../Data/Dataset LSTM Embedding_Label/Embeddings
    embeddings_shape: [ 128, 768 ]
  path_to_label: ../../Data/Dataset LSTM Embedding_Label/Labels

MetaModel:
  path_to_predictions_directory: ../../Data/MetaModel Predictions_Labels/Predictions
  path_to_labels_directory: ../../Data/MetaModel Predictions_Labels/Labels


