model_names:
    - roberta
    - sentiment
    - sexism

transformer:
    path_to_train: ../../Data/Data Transformers Text_Label/Train
    path_to_test: ../../Data/Data Transformers Text_Label/Test

    tokenizer :
        roberta : roberta-base
        sentiment : cardiffnlp/twitter-roberta-base-sentiment
        sexism : annahaz/xlm-roberta-base-misogyny-sexism-indomain-mix-bal

max_length : 128