path_to_content_root : ../../../
path_to_data : Data/Data Voting System
path_to_model_trained : Data/Model Trained/Meta model

train_size : 0.7
val_size : 0.1
batch_size : 64

model_parameters:
  train_hidden_dimensions:
    - 1024
    - 2048

  train_numbers_layers:
    - 1
    - 2
    - 3
    - 4
  max_epochs: 30
  learning_rate: 1e-5

wandb :
  project : "Training Metamodel"

scheduler:
  scheduler_name: ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 5
  verbose: true
  threshold: 1e-3
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  interval: epoch
  frequency: 1
  monitor: val_loss
  strict: true


