model_names:
  - roberta
  - sentiment
  - sexism

path_to_content_root : ../../../
path_to_embeddings : Data/Data LSTM Embedding_Label/Embeddings
path_to_labels : Data/Data LSTM Embedding_Label/Labels

model_class :
    classifier_outputs : 2

embedding_shape : [128, 768]
batch_size : 4

transformer:

  tokenizer:
    roberta: roberta-base
    sentiment: cardiffnlp/twitter-roberta-base-sentiment
    sexism: annahaz/xlm-roberta-base-misogyny-sexism-indomain-mix-bal