model_names:
  - roberta
  - sentiment
  - sexism

path_to_content_root : ../../../
path_to_embeddings : Data/Data LSTM Embedding_Label/Embeddings
path_to_labels : Data/Data LSTM Embedding_Label/Labels
path_to_save : Data/Data Voting System/LSTM
path_to_model_trained : Data/Model Trained/LSTM

model_class :
    classifier_outputs : 2

embedding_shape : [128, 768]
batch_size : 256


model_parameters:
  train_hidden_dimensions:
    - 8
  train_numbers_layers:
    - 1
  train_size : 0.5
  max_epochs: 10
  learning_rate: 1e-5
  dropout: 0.3
wandb :
  project : "Training LSTM"

scheduler:
  scheduler_name: ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 5
  verbose: true
  threshold: 1e-3
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  interval: epoch
  frequency: 1
  monitor: val_loss
  strict: true


